### ISSUE TITLE
Error with Biom format output from kraken2 report

### ISSUE THREAD

**Issue by UmaJan** [taxprofiler/taxpasta#144] opened 2024-02-02 13:51 UTC
### Checklist

- [X] I searched the [documentation](https://taxpasta.readthedocs.io).
- [X] I looked through existing [discussion topics](https://github.com/taxprofiler/taxpasta/discussions).
- [X] I looked for [similar issues](https://github.com/taxprofiler/taxpasta/issues).
- [X] I looked up my question/problem in a search engine.

### Question

[Question] I am having trouble with creating a biom output from a kraken2 file despite using pip install instructions as given in the readme. I have also made sure to use a pyenv 3.11.7 as that is one of the versiosn that is supported by biomformat. I have attached the error message below
![image](https://github.com/taxprofiler/taxpasta/assets/57330193/5ab5d210-a198-45f3-976e-75a01a785ebe)
![image](https://github.com/taxprofiler/taxpasta/assets/57330193/45229306-661d-45fc-a132-055385abbe53)

**Comment by jfy133** [comment] 2024-02-03 20:38
I think this is because only `taxpasta merge` supports BIOM... @Midnighter is there a reason why no BIOM for standardise? Does it only support multipl samples, for example?

**Comment by Midnighter** [comment] 2024-02-04 18:03
Yes, BIOM was intended as a format for groups of samples. That is why it's currently not implemented for `standardize`. Also see https://github.com/taxprofiler/taxpasta/issues/138#issuecomment-1741719063

**Comment by jfy133** [comment] 2024-02-04 18:10
Ok, I guess then close as not planned? I also agree with the comment it doesn't make much sense...

**Comment by Midnighter** [comment] 2024-02-04 20:08
Unless there is an overwhelming desire for having this, I would close it yeah. Although, it's coming up enough that we might want to put it in FAQ or similar?

**Closed** 2024-04-06 15:57 UTC
Labels: question
